/** Public portfolio projects — 25 across all industries + disciplines. */

export type ProjectSeed = {
  slug: string;
  title: string;
  industry: string; // industry slug
  disciplines: string[]; // discipline slugs
  services: string[]; // service slugs
  city: string;
  state: string;
  sizeSqft: number;
  floors: number;
  year: number;
  summary: string;
  scopeNotes: string;
  featured: boolean;
  sheet: string; // title-block sheet id, e.g. E-101
};

export const PROJECTS: ProjectSeed[] = [
  {
    slug: "brightbrew-drive-thru-electrical",
    title: "BrightBrew Coffee — Drive-Thru Electrical Fit-Out",
    industry: "franchise",
    disciplines: ["electrical", "lighting"],
    services: ["electrical-system-design", "lighting-design"],
    city: "Columbus", state: "OH", sizeSqft: 2100, floors: 1, year: 2025, featured: true, sheet: "E-101",
    summary: "Prototype-based power, equipment and lighting set adapted to an Ohio drive-thru for the BrightBrew franchise rollout.",
    scopeNotes: "Panel schedules, drive-thru menu-board and timer circuits, espresso-line equipment connections, interior + canopy lighting.",
  },
  {
    slug: "stackhouse-burgers-inline-mep",
    title: "Stackhouse Burgers — Inline Restaurant MEP",
    industry: "franchise",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["electrical-system-design", "mechanical-design"],
    city: "Tampa", state: "FL", sizeSqft: 1450, floors: 1, year: 2024, featured: false, sheet: "E-101",
    summary: "Full electrical, HVAC and plumbing adaptation of the brand prototype for an inline shell in a Florida plaza.",
    scopeNotes: "Make-up air balance, kitchen-line equipment power, hand-sink and prep plumbing to the franchise standard.",
  },
  {
    slug: "single-dwelling-electrical-plumbing",
    title: "Single Dwelling — Electrical & Plumbing",
    industry: "residential",
    disciplines: ["electrical", "plumbing"],
    services: ["electrical-system-design", "plumbing-design", "electrical-load-calculation"],
    city: "Naples", state: "FL", sizeSqft: 3900, floors: 2, year: 2025, featured: true, sheet: "E-101",
    summary: "Two-story custom home power, plumbing and NEC load calc for permit.",
    scopeNotes: "Panel schedule and circuiting, fixture and lighting plan, supply and waste routing, NEC 220 load calc.",
  },
  {
    slug: "adu-hvac-load-and-layout",
    title: "Backyard ADU — HVAC Load & Layout",
    industry: "residential",
    disciplines: ["hvac"],
    services: ["hvac-design", "hvac-heating-cooling-load"],
    city: "Portland", state: "OR", sizeSqft: 780, floors: 1, year: 2024, featured: false, sheet: "M-101",
    summary: "Manual-J load and mini-split HVAC layout for an accessory dwelling unit.",
    scopeNotes: "Room-by-room Manual-J, ductless equipment sizing and placement, ventilation.",
  },
  {
    slug: "midtown-office-ti-lighting-controls",
    title: "Midtown Office TI — Lighting & Controls",
    industry: "offices",
    disciplines: ["electrical", "lighting"],
    services: ["lighting-design", "photometric-design"],
    city: "New York", state: "NY", sizeSqft: 3800, floors: 1, year: 2025, featured: true, sheet: "E-101",
    summary: "Open-plan office lighting with daylight and occupancy controls, plus a footcandle study.",
    scopeNotes: "Fixture layout, daylight and occupancy control zones, switching plan, point-by-point footcandle grid.",
  },
  {
    slug: "coworking-suite-power-data",
    title: "Coworking Suite — Power & Data",
    industry: "offices",
    disciplines: ["electrical"],
    services: ["electrical-system-design", "single-line-diagram"],
    city: "Denver", state: "CO", sizeSqft: 3400, floors: 1, year: 2024, featured: false, sheet: "E-101",
    summary: "Flexible power and furniture-whip distribution with a revised one-line for a coworking suite.",
    scopeNotes: "Floor boxes and furniture whips, panel schedule, revised one-line, data pathway coordination.",
  },
  {
    slug: "farmhouse-kitchen-restaurant-mep",
    title: "Farmhouse Kitchen — Restaurant MEP",
    industry: "restaurant",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["electrical-system-design", "mechanical-design"],
    city: "Nashville", state: "TN", sizeSqft: 3600, floors: 1, year: 2025, featured: true, sheet: "E-101",
    summary: "Type-I hood exhaust, make-up air, kitchen power and grease/gas plumbing for a full-service restaurant.",
    scopeNotes: "Type-I hood exhaust + MUA balance, heavy equipment circuits, grease waste and gas piping.",
  },
  {
    slug: "cafe-hood-exhaust-suppression",
    title: "Corner Café — Hood Exhaust & Suppression",
    industry: "restaurant",
    disciplines: ["hvac", "fire-protection"],
    services: ["hvac-design", "sprinkler-layout-plan"],
    city: "Seattle", state: "WA", sizeSqft: 1900, floors: 1, year: 2024, featured: false, sheet: "M-101",
    summary: "Kitchen exhaust and make-up air with sprinkler coverage for a small café tenant.",
    scopeNotes: "Type-II hood exhaust, MUA, tenant sprinkler layout to NFPA 13.",
  },
  {
    slug: "urgent-care-electrical-lifesafety",
    title: "Urgent Care Clinic — Electrical & Life-Safety",
    industry: "healthcare",
    disciplines: ["electrical", "fire-protection"],
    services: ["electrical-system-design", "fire-alarm-system-design"],
    city: "Charlotte", state: "NC", sizeSqft: 3600, floors: 1, year: 2025, featured: true, sheet: "E-101",
    summary: "Dedicated power, egress lighting and an NFPA 72 fire-alarm set for an urgent-care fit-out.",
    scopeNotes: "Exam-room circuits, egress and emergency lighting, NFPA 72 device layout, battery calc.",
  },
  {
    slug: "dental-office-plumbing-hvac",
    title: "Dental Office — Plumbing & HVAC",
    industry: "healthcare",
    disciplines: ["hvac", "plumbing"],
    services: ["hvac-design", "plumbing-design"],
    city: "Phoenix", state: "AZ", sizeSqft: 3200, floors: 1, year: 2024, featured: false, sheet: "M-101",
    summary: "Operatory plumbing, vacuum/air and zoned HVAC for a multi-chair dental practice.",
    scopeNotes: "Per-chair water/waste, dedicated exhaust, zoned comfort HVAC, ventilation.",
  },
  {
    slug: "day-spa-plumbing-ventilation",
    title: "Day Spa — Plumbing & Ventilation",
    industry: "salon",
    disciplines: ["hvac", "plumbing"],
    services: ["hvac-design", "plumbing-design"],
    city: "Scottsdale", state: "AZ", sizeSqft: 2600, floors: 1, year: 2025, featured: false, sheet: "M-101",
    summary: "Multi-bowl plumbing, hot-water sizing and fume ventilation for a day spa.",
    scopeNotes: "Wash-bowl risers, hot-water demand, chemical-fume exhaust and make-up air.",
  },
  {
    slug: "salon-suite-station-power",
    title: "Salon Suites — Station Power & Lighting",
    industry: "salon",
    disciplines: ["electrical", "lighting"],
    services: ["electrical-system-design", "lighting-design"],
    city: "Jacksonville", state: "FL", sizeSqft: 3700, floors: 1, year: 2024, featured: false, sheet: "E-101",
    summary: "Per-suite dedicated station power and flattering, even lighting for a salon-suite concept.",
    scopeNotes: "Dedicated station circuits, suite panel schedule, mirror and ambient lighting layout.",
  },
  {
    slug: "ridgeline-storage-yard-lighting",
    title: "Ridgeline Self-Storage — Yard Lighting & Photometrics",
    industry: "warehouse",
    disciplines: ["lighting"],
    services: ["lighting-design", "photometric-design"],
    city: "Orlando", state: "FL", sizeSqft: 2900, floors: 1, year: 2024, featured: false, sheet: "E-201",
    summary: "Drive-aisle and yard lighting with a photometric study for a small self-storage site.",
    scopeNotes: "Drive-aisle pole and wall-pack layout, photometric grid across the yard, fixture schedule, light-trespass check at the boundary.",
  },
  {
    slug: "garden-apartments-13r-sprinkler",
    title: "Garden Apartment Block — 13R Sprinkler & Alarm",
    industry: "apartments",
    disciplines: ["fire-protection"],
    services: ["fire-alarm-system-design", "sprinkler-layout-plan"],
    city: "Atlanta", state: "GA", sizeSqft: 3900, floors: 2, year: 2025, featured: true, sheet: "FP-101",
    summary: "NFPA 13R sprinkler layout with hydraulic report and fire-alarm coverage for a small garden apartment block.",
    scopeNotes: "13R head layout per unit, riser detail, hydraulic calculation, alarm device coverage.",
  },
  {
    slug: "apartment-unit-stack-electrical",
    title: "Apartment Unit Stack — Electrical",
    industry: "apartments",
    disciplines: ["electrical"],
    services: ["electrical-system-design", "single-line-diagram", "electrical-load-calculation"],
    city: "Minneapolis", state: "MN", sizeSqft: 3400, floors: 3, year: 2024, featured: false, sheet: "E-101",
    summary: "Repeatable unit panels, house distribution and a service load calc for a three-story apartment stack.",
    scopeNotes: "Typical unit panel schedule, riser through three floors, house panel, service load tabulation.",
  },
  {
    slug: "plaza-pad-site-electrical",
    title: "Plaza Pad Site — Electrical & Photometrics",
    industry: "plaza",
    disciplines: ["electrical", "lighting"],
    services: ["site-electrical-plan", "photometric-design"],
    city: "Fort Myers", state: "FL", sizeSqft: 2900, floors: 1, year: 2025, featured: true, sheet: "E-101",
    summary: "Pad-site power, sign feed and a parking photometric study for a single plaza tenant.",
    scopeNotes: "Service entrance, sign and site-lighting feeds, point-by-point photometric grid for the tenant's parking bays.",
  },
  {
    slug: "retail-tenant-sprinkler-alarm",
    title: "Retail Tenant — Sprinkler & Alarm",
    industry: "plaza",
    disciplines: ["fire-protection"],
    services: ["fire-alarm-system-design", "sprinkler-layout-plan"],
    city: "Las Vegas", state: "NV", sizeSqft: 2400, floors: 1, year: 2024, featured: false, sheet: "FP-101",
    summary: "Tenant sprinkler layout and fire-alarm coverage for a retail unit in a multi-tenant plaza.",
    scopeNotes: "Tenant head layout off the shell main, alarm devices, riser tie-in, coverage check.",
  },
  {
    slug: "little-sprouts-daycare-mep",
    title: "Little Sprouts Daycare — Complete MEP",
    industry: "commercial",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["electrical-system-design", "mechanical-design", "plumbing-design"],
    city: "Sarasota", state: "FL", sizeSqft: 3400, floors: 1, year: 2025, featured: false, sheet: "E-101",
    summary: "Full electrical, HVAC and plumbing set for a licensed childcare centre with classroom, nap and kitchen zones.",
    scopeNotes: "Classroom power and lighting, kitchen equipment connections, zoned HVAC with fresh-air rates, child-height fixture plumbing, egress lighting.",
  },
  {
    slug: "mercado-plaza-power-upgrade",
    title: "Mercado Plaza — 600A Service Upgrade",
    industry: "plaza",
    disciplines: ["electrical"],
    services: ["single-line-diagram", "power-upgrade", "electrical-load-calculation"],
    city: "Fort Myers", state: "FL", sizeSqft: 3800, floors: 1, year: 2025, featured: false, sheet: "E-101",
    summary: "Service upgrade from 200A to 600A for a multi-tenant retail unit, with existing-versus-new one-line and load basis.",
    scopeNotes: "Existing vs. new one-line, meter bank relocation, feeder routing and conduit schedule, updated panel schedules, demand load tabulation.",
  },
  {
    slug: "bayside-dental-studio-mep",
    title: "Bayside Dental Studio — Complete MEP",
    industry: "healthcare",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["electrical-system-design", "mechanical-design", "plumbing-design"],
    city: "Naples", state: "FL", sizeSqft: 3200, floors: 1, year: 2025, featured: false, sheet: "E-101",
    summary: "Complete electrical, mechanical and plumbing set for a six-operatory dental practice.",
    scopeNotes: "Operatory power and data, vacuum and compressed-air lines, sterilisation room plumbing, zoned HVAC with dedicated exhaust, panel schedules.",
  },
  {
    slug: "ocala-plaza-site-photometrics",
    title: "Ocala Plaza — Site Electrical & Photometrics",
    industry: "plaza",
    disciplines: ["electrical", "lighting"],
    services: ["site-electrical-plan", "photometric-design"],
    city: "Ocala", state: "FL", sizeSqft: 3600, floors: 1, year: 2024, featured: false, sheet: "E-101",
    summary: "Site electrical plan and a point-by-point photometric study for a neighbourhood retail plaza.",
    scopeNotes: "Site power distribution, pylon-sign and bollard feeds, pole-base details, parking photometric grid with light-trespass check at the property line.",
  },
  {
    slug: "maple-row-townhomes-mep",
    title: "Maple Row Townhomes — Complete MEP",
    industry: "residential",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["electrical-system-design", "mechanical-design", "plumbing-design"],
    city: "Jacksonville", state: "FL", sizeSqft: 3900, floors: 2, year: 2025, featured: false, sheet: "E-101",
    summary: "Full electrical, HVAC and plumbing set for a row of two-story townhomes, drafted once and repeated per unit.",
    scopeNotes: "Per-unit panel schedules and circuiting, split-system HVAC with room-by-room load basis, supply and waste risers between floors, water heater and fixture connections, exterior entry lighting.",
  },
  {
    slug: "coastal-commons-ev-charging",
    title: "Coastal Commons — 4-Stall EV Charging",
    industry: "plaza",
    disciplines: ["electrical"],
    services: ["site-electrical-plan", "single-line-diagram", "electrical-load-calculation"],
    city: "Tampa", state: "FL", sizeSqft: 2600, floors: 1, year: 2025, featured: false, sheet: "E-101",
    summary: "Four Level 2 EV charging stalls added to an existing retail lot, with feeder routing and the load basis for the added demand.",
    scopeNotes: "Four dual-port Level 2 stations, dedicated feeders and trenching route, charger panel and disconnects, service load calc for the added demand, bollard and ADA stall details.",
  },
  {
    slug: "beacon-street-offices-mep",
    title: "Beacon Street Offices — Complete MEP",
    industry: "offices",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["electrical-system-design", "mechanical-design", "plumbing-design"],
    city: "Orlando", state: "FL", sizeSqft: 3700, floors: 1, year: 2024, featured: false, sheet: "E-101",
    summary: "Full MEP set for a professional office suite with meeting rooms, break area and server closet.",
    scopeNotes: "Power and data layout, server-closet cooling, zoned HVAC, break-room plumbing, lighting and switching plan, panel schedules.",
  },
  {
    slug: "copper-skillet-load-calc-electrical",
    title: "Copper Skillet Kitchen — Load Calc & Electrical",
    industry: "restaurant",
    disciplines: ["electrical"],
    services: ["electrical-system-design", "single-line-diagram", "electrical-load-calculation"],
    city: "Miami", state: "FL", sizeSqft: 2900, floors: 1, year: 2025, featured: false, sheet: "E-101",
    summary: "Full NEC load calculation and electrical set for a kitchen-heavy restaurant fit-out.",
    scopeNotes: "Kitchen equipment schedule and connections, NEC 220 demand load calc, service one-line, panel schedules, dining and back-of-house lighting circuits.",
  },
];
