/** Public portfolio projects — 24 across all industries + disciplines. */

export type ProjectSeed = {
  slug: string;
  title: string;
  industry: string; // industry slug
  disciplines: string[]; // discipline slugs
  services: string[]; // service slugs
  city: string;
  state: string;
  sizeSqft: number;
  floors: number;
  year: number;
  summary: string;
  scopeNotes: string;
  featured: boolean;
  sheet: string; // title-block sheet id, e.g. E-101
};

export const PROJECTS: ProjectSeed[] = [
  {
    slug: "brightbrew-drive-thru-electrical",
    title: "BrightBrew Coffee — Drive-Thru Electrical Fit-Out",
    industry: "franchise",
    disciplines: ["electrical", "lighting"],
    services: ["electrical-system-design", "lighting-design"],
    city: "Columbus", state: "OH", sizeSqft: 2100, floors: 1, year: 2025, featured: true, sheet: "E-101",
    summary: "Prototype-based power, equipment and lighting set adapted to an Ohio drive-thru for the BrightBrew franchise rollout.",
    scopeNotes: "Panel schedules, drive-thru menu-board and timer circuits, espresso-line equipment connections, interior + canopy lighting.",
  },
  {
    slug: "stackhouse-burgers-inline-mep",
    title: "Stackhouse Burgers — Inline Restaurant MEP",
    industry: "franchise",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["mechanical-design", "electrical-system-design"],
    city: "Tampa", state: "FL", sizeSqft: 1450, floors: 1, year: 2024, featured: false, sheet: "M-101",
    summary: "Full electrical, HVAC and plumbing adaptation of the brand prototype for an inline shell in a Florida plaza.",
    scopeNotes: "Make-up air balance, kitchen-line equipment power, hand-sink and prep plumbing to the franchise standard.",
  },
  {
    slug: "custom-lakehouse-electrical-plumbing",
    title: "Custom Lakehouse — Electrical & Plumbing",
    industry: "residential",
    disciplines: ["electrical", "plumbing"],
    services: ["electrical-system-design", "plumbing-design", "electrical-load-calculation"],
    city: "Austin", state: "TX", sizeSqft: 4800, floors: 2, year: 2025, featured: true, sheet: "E-201",
    summary: "Two-story custom home power, plumbing and NEC load calc for permit.",
    scopeNotes: "200A service load calc, whole-house lighting, well and fixture plumbing risers.",
  },
  {
    slug: "adu-hvac-load-and-layout",
    title: "Backyard ADU — HVAC Load & Layout",
    industry: "residential",
    disciplines: ["hvac"],
    services: ["hvac-design", "hvac-heating-cooling-load"],
    city: "Portland", state: "OR", sizeSqft: 780, floors: 1, year: 2024, featured: false, sheet: "M-201",
    summary: "Manual-J load and mini-split HVAC layout for an accessory dwelling unit.",
    scopeNotes: "Room-by-room Manual-J, ductless equipment sizing and placement, ventilation.",
  },
  {
    slug: "midtown-office-ti-lighting-controls",
    title: "Midtown Office TI — Lighting & Controls",
    industry: "offices",
    disciplines: ["lighting", "electrical"],
    services: ["lighting-design", "photometric-design"],
    city: "New York", state: "NY", sizeSqft: 12500, floors: 1, year: 2025, featured: true, sheet: "E-301",
    summary: "Open-plan office lighting with daylight and occupancy controls, plus a footcandle study.",
    scopeNotes: "Tunable troffer layout, daylight zones, occupancy sensing, point-by-point photometrics.",
  },
  {
    slug: "coworking-floor-power-data",
    title: "Coworking Floor — Power & Data",
    industry: "offices",
    disciplines: ["electrical"],
    services: ["electrical-system-design", "single-line-diagram"],
    city: "Denver", state: "CO", sizeSqft: 9800, floors: 1, year: 2024, featured: false, sheet: "E-302",
    summary: "Flexible power and furniture-whip distribution with a revised one-line for a coworking build-out.",
    scopeNotes: "Floor-box and whip layout, panel additions, updated single line diagram.",
  },
  {
    slug: "farmhouse-kitchen-restaurant-mep",
    title: "Farmhouse Kitchen — Restaurant MEP",
    industry: "restaurant",
    disciplines: ["electrical", "hvac", "plumbing"],
    services: ["mechanical-design", "electrical-system-design"],
    city: "Nashville", state: "TN", sizeSqft: 3600, floors: 1, year: 2025, featured: true, sheet: "M-401",
    summary: "Type-I hood exhaust, make-up air, kitchen power and grease/gas plumbing for a full-service restaurant.",
    scopeNotes: "Type-I hood exhaust + MUA balance, heavy equipment circuits, grease waste and gas piping.",
  },
  {
    slug: "cafe-hood-exhaust-suppression",
    title: "Corner Café — Hood Exhaust & Suppression",
    industry: "restaurant",
    disciplines: ["hvac", "fire-protection"],
    services: ["hvac-design", "sprinkler-layout-plan"],
    city: "Seattle", state: "WA", sizeSqft: 1900, floors: 1, year: 2024, featured: false, sheet: "M-402",
    summary: "Kitchen exhaust and make-up air with sprinkler coverage for a small café tenant.",
    scopeNotes: "Type-II hood exhaust, MUA, tenant sprinkler layout to NFPA 13.",
  },
  {
    slug: "urgent-care-electrical-lifesafety",
    title: "Urgent Care Clinic — Electrical & Life-Safety",
    industry: "healthcare",
    disciplines: ["electrical", "fire-protection"],
    services: ["electrical-system-design", "fire-alarm-system-design"],
    city: "Charlotte", state: "NC", sizeSqft: 6400, floors: 1, year: 2025, featured: true, sheet: "E-501",
    summary: "Dedicated power, egress lighting and an NFPA 72 fire-alarm set for an urgent-care fit-out.",
    scopeNotes: "Isolated/dedicated circuits, egress and exit lighting, fire alarm device plan + battery calc.",
  },
  {
    slug: "dental-office-plumbing-hvac",
    title: "Dental Office — Plumbing & HVAC",
    industry: "healthcare",
    disciplines: ["plumbing", "hvac"],
    services: ["plumbing-design", "hvac-design"],
    city: "Phoenix", state: "AZ", sizeSqft: 3200, floors: 1, year: 2024, featured: false, sheet: "P-501",
    summary: "Operatory plumbing, vacuum/air and zoned HVAC for a multi-chair dental practice.",
    scopeNotes: "Per-chair water/waste, dedicated exhaust, zoned comfort HVAC, ventilation.",
  },
  {
    slug: "day-spa-plumbing-ventilation",
    title: "Day Spa — Plumbing & Ventilation",
    industry: "salon",
    disciplines: ["plumbing", "hvac"],
    services: ["plumbing-design", "hvac-design"],
    city: "Scottsdale", state: "AZ", sizeSqft: 2600, floors: 1, year: 2025, featured: false, sheet: "P-601",
    summary: "Multi-bowl plumbing, hot-water sizing and fume ventilation for a day spa.",
    scopeNotes: "Wash-bowl risers, hot-water demand, chemical-fume exhaust and make-up air.",
  },
  {
    slug: "salon-suite-station-power",
    title: "Salon Suites — Station Power & Lighting",
    industry: "salon",
    disciplines: ["electrical", "lighting"],
    services: ["electrical-system-design", "lighting-design"],
    city: "Dallas", state: "TX", sizeSqft: 4100, floors: 1, year: 2024, featured: false, sheet: "E-601",
    summary: "Per-suite dedicated station power and flattering, even lighting for a salon-suite concept.",
    scopeNotes: "Dedicated station circuits, mirror lighting, sub-metering per suite.",
  },
  {
    slug: "boutique-hotel-typical-floor",
    title: "Boutique Hotel — Typical Floor MEP",
    industry: "hotel",
    disciplines: ["electrical", "plumbing", "fire-protection"],
    services: ["electrical-system-design", "plumbing-design", "sprinkler-layout-plan"],
    city: "Miami", state: "FL", sizeSqft: 14200, floors: 1, year: 2025, featured: true, sheet: "E-701",
    summary: "Repeatable guestroom electrical and plumbing stacks with full NFPA 13 sprinkler coverage.",
    scopeNotes: "Guestroom power/plumbing stacks, corridor lighting, typical-floor sprinkler layout.",
  },
  {
    slug: "resort-amenity-lighting-photometrics",
    title: "Resort Amenity Deck — Lighting & Photometrics",
    industry: "hotel",
    disciplines: ["lighting"],
    services: ["lighting-design", "photometric-design"],
    city: "Orlando", state: "FL", sizeSqft: 8800, floors: 1, year: 2024, featured: false, sheet: "E-702",
    summary: "Pool-deck and amenity lighting with a photometric study for safety and ambience.",
    scopeNotes: "Landscape and pool-deck fixtures, footcandle grid, light-trespass check.",
  },
  {
    slug: "garden-apartments-13r-sprinkler",
    title: "Garden Apartments — 13R Sprinkler & Alarm",
    industry: "apartments",
    disciplines: ["fire-protection"],
    services: ["sprinkler-layout-plan", "fire-alarm-system-design"],
    city: "Atlanta", state: "GA", sizeSqft: 16800, floors: 3, year: 2025, featured: true, sheet: "FP-801",
    summary: "NFPA 13R sprinkler layout with hydraulic report and building fire-alarm coverage.",
    scopeNotes: "13R head layout, hydraulic calc vs. supply, corridor/unit alarm devices + riser.",
  },
  {
    slug: "midrise-apartments-unit-electrical",
    title: "Mid-Rise Apartments — Unit Electrical Stacks",
    industry: "apartments",
    disciplines: ["electrical"],
    services: ["electrical-system-design", "electrical-load-calculation", "single-line-diagram"],
    city: "Minneapolis", state: "MN", sizeSqft: 21000, floors: 5, year: 2024, featured: false, sheet: "E-801",
    summary: "Repeatable unit panels, house distribution and service load calc for a five-story building.",
    scopeNotes: "Unit + house metering, riser one-line, NEC service load calculation.",
  },
  {
    slug: "cnc-shop-power-distribution",
    title: "CNC Machine Shop — Power Distribution",
    industry: "industrial",
    disciplines: ["electrical"],
    services: ["electrical-system-design", "single-line-diagram", "electrical-load-calculation"],
    city: "Cleveland", state: "OH", sizeSqft: 18500, floors: 1, year: 2025, featured: true, sheet: "E-901",
    summary: "Machine-tool feeders, distribution one-line and load calc for a metal-fabrication shop.",
    scopeNotes: "Motor feeders and disconnects, distribution one-line, connected/demand load calc.",
  },
  {
    slug: "process-plant-exhaust-piping",
    title: "Process Plant — Exhaust & Process Piping",
    industry: "industrial",
    disciplines: ["hvac", "plumbing"],
    services: ["hvac-design", "plumbing-design"],
    city: "Houston", state: "TX", sizeSqft: 24000, floors: 1, year: 2024, featured: false, sheet: "M-901",
    summary: "Process exhaust, make-up air and compressed-air/process piping for a light-industrial plant.",
    scopeNotes: "Process exhaust and MUA, compressed-air distribution, floor process piping.",
  },
  {
    slug: "strip-plaza-site-photometrics",
    title: "Strip Plaza — Site Electrical & Photometrics",
    industry: "plaza",
    disciplines: ["electrical", "lighting"],
    services: ["site-electrical-plan", "photometric-design"],
    city: "Sacramento", state: "CA", sizeSqft: 32000, floors: 1, year: 2025, featured: true, sheet: "ES-101",
    summary: "Multi-tenant site power, pylon-sign feeds and a parking-lot photometric study.",
    scopeNotes: "Site distribution and metering, sign power, parking photometrics + trespass check.",
  },
  {
    slug: "retail-plaza-tenant-fire",
    title: "Retail Plaza — Tenant Sprinkler & Alarm",
    industry: "plaza",
    disciplines: ["fire-protection"],
    services: ["sprinkler-layout-plan", "fire-alarm-system-design"],
    city: "Las Vegas", state: "NV", sizeSqft: 15200, floors: 1, year: 2024, featured: false, sheet: "FP-102",
    summary: "Shell-and-tenant sprinkler layout and fire-alarm coverage for a retail plaza.",
    scopeNotes: "Shell + per-tenant sprinkler grid, tenant alarm devices tied to the base system.",
  },
  {
    slug: "corporate-hq-hvac-load",
    title: "Corporate HQ — HVAC Design & Load",
    industry: "commercial",
    disciplines: ["hvac"],
    services: ["hvac-design", "hvac-heating-cooling-load"],
    city: "Chicago", state: "IL", sizeSqft: 28500, floors: 2, year: 2025, featured: true, sheet: "M-110",
    summary: "Zoned VAV HVAC with ASHRAE load basis across two floors of corporate office.",
    scopeNotes: "ASHRAE block/zone loads, VAV distribution, ventilation and controls layout.",
  },
  {
    slug: "core-shell-single-line",
    title: "Core & Shell — Service & Single Line",
    industry: "commercial",
    disciplines: ["electrical"],
    services: ["single-line-diagram", "electrical-load-calculation", "site-electrical-plan"],
    city: "Raleigh", state: "NC", sizeSqft: 40000, floors: 3, year: 2024, featured: false, sheet: "E-110",
    summary: "Building service one-line, load calc and site electrical for a core-and-shell development.",
    scopeNotes: "Service one-line, NEC load calc, site power routing to the utility POC.",
  },
  {
    slug: "distribution-center-esfr-highbay",
    title: "Distribution Center — ESFR & High-Bay Lighting",
    industry: "warehouse",
    disciplines: ["fire-protection", "lighting"],
    services: ["sprinkler-layout-plan", "photometric-design"],
    city: "Indianapolis", state: "IN", sizeSqft: 65000, floors: 1, year: 2025, featured: true, sheet: "FP-120",
    summary: "ESFR sprinkler layout with hydraulic report and a high-bay photometric grid for a distribution center.",
    scopeNotes: "ESFR head layout, hydraulic calc vs. supply, high-bay lighting photometrics.",
  },
  {
    slug: "mercado-plaza-power-upgrade",
    title: "Mercado Plaza — 600A Service Upgrade",
    industry: "plaza",
    disciplines: ["electrical"],
    services: ["power-upgrade", "electrical-system-design", "single-line-diagram"],
    city: "Phoenix", state: "AZ", sizeSqft: 27000, floors: 1, year: 2025, featured: false, sheet: "E-104",
    summary: "600A service upgrade with new distribution and tenant metering for a busy retail plaza.",
    scopeNotes: "Service upgrade one-line, panel and feeder schedule, tenant metering layout.",
  },
  {
    slug: "plaza-pad-site-electrical",
    title: "Plaza Pad Site — Electrical & Photometrics",
    industry: "plaza",
    disciplines: ["electrical", "lighting"],
    services: ["site-electrical-plan", "photometric-design"],
    city: "Dallas", state: "TX", sizeSqft: 18500, floors: 1, year: 2025, featured: false, sheet: "ES-105",
    summary: "Pad-site power distribution and a parking photometric study for a new plaza outparcel.",
    scopeNotes: "Site distribution, drive-thru and sign feeds, parking photometrics + trespass check.",
  },
  {
    slug: "retail-tenant-sprinkler-alarm",
    title: "Retail Tenant — Sprinkler & Alarm",
    industry: "plaza",
    disciplines: ["fire-protection"],
    services: ["sprinkler-layout-plan", "fire-alarm-system-design"],
    city: "Orlando", state: "FL", sizeSqft: 9800, floors: 1, year: 2024, featured: false, sheet: "FP-106",
    summary: "Tenant sprinkler layout and fire-alarm coverage for a retail end-cap suite.",
    scopeNotes: "Tenant sprinkler grid, alarm device layout tied to the base-building system.",
  },
  {
    slug: "ridgeline-storage-yard-lighting",
    title: "Ridgeline Self-Storage — Yard Lighting & Photometrics",
    industry: "warehouse",
    disciplines: ["electrical", "lighting"],
    services: ["site-electrical-plan", "lighting-design", "photometric-design"],
    city: "Nashville", state: "TN", sizeSqft: 42000, floors: 1, year: 2025, featured: false, sheet: "ES-107",
    summary: "Yard lighting layout and photometric study for a self-storage facility's drive aisles.",
    scopeNotes: "Pole layout and circuiting, aisle photometrics, light-trespass compliance.",
  },
];
